export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const SET_USER_LIST = "SET_USER_LIST";
export const SET_USER_DATA = "SET_USER_DATA";
export const ENABLE_EDIT_FORM = "SET_EDIT_FORM";
export const FETCH_ALL_USERS = "FETCH_ALL_USERS";
export const FETCH_sINGLE_USER = "FETCH_sINGLE_USER";