export const TEST_QUESTION_POPUP = "TEST_QUESTION_POPUP";
export const TEST_QUESTION_ENABLE = "TEST_QUESTION_ENABLE";
export const TEST_QUESTION_CREATE = "TEST_QUESTION_CREATE";
export const TEST_QUESTION_ALL_TEST = "TEST_QUESTION_ALL_TEST";
export const TEST_QUESTION_GET_SINGLE_TEST_RESULT =
  "TEST_QUESTION_GET_SINGLE_TEST_RESULT";
export const FETCH_ALL_TEST = "FETCH_ALL_TEST";
export const FETCH_SINGLE_TEST = "FETCH_SINGLE_TEST";
export const CREATE_TEST = "CREATE_TEST";
export const COMPILED_CODE_OUTPUT = "COMPILED_CODE_OUTPUT";
export const STORE_TEST_RESULT = "STORE_TEST_RESULT";
export const CLOSE_TEST_CASES_AREA = "CLOSE_TEST_CASES_AREA";
// export const TEST_QUESTION_ = "TEST_QUESTION_POPUP";
